[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dev-data-embed"
version = "1.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlite-vec",
    "sentence-transformers",
    "google-auth",
    "pyjwt",
    "requests",
    "langchain-openai",
    "langchain-text-splitters",
    "transformers",
    "google-auth",
    "pyjwt",
    "requests",
]


[tool.setuptools.packages.find]
include = ["app*","pipeline*"]
namespaces= true