[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dev-data-embed"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlite-vec",
    "sentence-transformers",
    "google-auth",
    "pyjwt",
    "requests",
    "supabase",
]

[tool.setuptools.packages.find]
include = ["app*","pipeline*"]
namespaces= true